# Generated by Django 4.1.5 on 2023-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youMap_app', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_content',
            field=models.CharField(default='no comment', max_length=500),
        ),
    ]
